import sys
import argparse

parser = argparse.ArgumentParser(prog='Segno Processor')
parser.add_argument('--grammar_py', required=True,  help='location of the python generated by antlr')
parser.add_argument('--input',      required=True,  help='location of the input file')
parser.add_argument('--out_debug',  required=False, help='output path for debug info')
parser.add_argument('--out_decl',   required=False, help='output path for the declarative header file')
parser.add_argument('--out_impl',   required=False, help='output path for the implementation header file')
parser.add_argument('--verbose',    required=False, help='enable verbose log printing', action='store_true')
args = parser.parse_args()

sys.path.insert(0, args.grammar_py)

import antlr4
from segno_grammarLexer   import segno_grammarLexer
from segno_grammarParser  import segno_grammarParser

from segno                import debug         as seg_debug

with open(args.input) as file:
  data = file.read()
  
lexer  = segno_grammarLexer(antlr4.InputStream(data))
stream = antlr4.CommonTokenStream(lexer)
parser = segno_grammarParser(stream)
tree   = parser.prog()

# debug
if args.verbose:
  visitor = seg_debug.segno_debug_visitor(parser)
  visitor.visit(tree)
